### ISSUE TITLE
OpenSC fails to re-authenticate for CKA_ALWAYS_AUTHENTICATE keys

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1039]
### Scenario
A token with at least two keys:
- `KEY MAN key` that requires authentication before it is used for the first time during this session;
- `SIGN key` (with `CKA_ALWAYS_AUTHENTICATE` set) that requires (re-)authentication every time it performs an operation.

### Expected behaviour

Regardless of whether the token has been "logged in" or not, user should be prompted for PIN when an operation with a `CKA_ALWAYS_AUTHENTICATE` key is attempted.

### Actual behaviour

User is **not** prompted for the PIN, and the operation fails with the error code "User not logged in".

Note that if `	pin_cache_ignore_user_consent = true;` is set in `/Library/OpenSC/etc/opensc.conf`, then the signing operation succeeds (for obvious reason). This is why I haven't caught this bug before. But considering security implications of this workaround - it would be unadvisable to rely on it.

### Steps to reproduce

Since it happens only when the token has already been logged in (e.g., for operations with the decryption key), I run a test-program that uses `libp11` and `OpenSSL`. The problem seems to be with `OpenSC`. If you check `libp11/src/p11_rsa.c` around line 120: it calls `pkcs11_authenticate()` at all the right spots.

1. Compile and install OpenSC, libp11, OpenSSL (in reverse order :).
2. Run test-program that 
    a. encrypts some data using public key `KEY MAN pubkey` on the token;
    b. decrypts that data using private key `KEY MAN key` on the token (*at this point user is prompted for a PIN);
    c. signs some data using private key `SIGN key` on the token (*at this point user **should** be prompted for the PIN again, but the prompt is **not** offered - which is the problem I'm complaining about*);
   d. verifies that signature using public key `SIGN pubkey` on the token.
3. Observe failure at 2.c.

### Logs

This is the complete screen log (error reported by `libp11`):
```
$ PKCS11_MODULE_PATH=/Library/OpenSC/lib/pkcs11-spy.so PKCS11SPY_OUTPUT=~/aa-spy.txt OSSL-Tst2 
Generated random 256-bit AES key:
f4 29 bd 87 e6 48 b6 30 74 74 da 67 85 e9 d2 c7 
da c8 52 3f 56 53 e6 22 6e 6b cb 3f 1e 66 48 ec 

Symmetric key encrypted with RSA-OAEP (256 bytes):
42 c4 4f f2 7b b0 8c ec 8c 5a b7 6b 79 42 47 10 
. . . . .
2f 8a 3c 07 4d 82 81 b8 49 22 6d 53 7c 59 25 31 

Enter PKCS#11 token PIN for PIV Card Holder pin (PIV_II):
Decrypted symmetric key (32 bytes):
f4 29 bd 87 e6 48 b6 30 74 74 da 67 85 e9 d2 c7 
da c8 52 3f 56 53 e6 22 6e 6b cb 3f 1e 66 48 ec 

Decrypted key matches the original.

sign: failed to sign (rv=-1)
140736466609160:error:80009101:Vendor defined:PKCS11_rsa_encrypt:User not logged in:p11_rsa.c:120:
Signing failed! (rv=-1 olen=256)

$
```
SPY:  [aa-spy.txt](https://github.com/OpenSC/OpenSC/files/963412/aa-spy.txt)
opensc-debug.log: 
[opensc-aa3.txt](https://github.com/OpenSC/OpenSC/files/963452/opensc-aa3.txt)

@mtrojnar, copying you since `libp11` is involved, and it *might* be that `pkcs11_authenticate()` in `libp11/src/p11_key.c` is at fault.

@dengert you might know (or be able to figure out quicker) what's going on. According to SPY, when it came to signing, the call sequence was:

1. Checked for `CKA_ALWAYS_AUTHENTICATE` - got back `True` and `CKR_OK`;
2. Issued `C_SignInit()` - got back `CKR_OK`;
3. Issued `C_Sign()` - and got back `CKR_USER_NOT_LOGGED_IN`.

I was under impression that if the user is not logged in, then `C_SignInit()` must fail with `CKR_USER_NOT_LOGGED_IN`...?

**Comment by frankmorgner** [comment]
What test program are you referring to? Can you reproduce the problem with pure OpenSC?

Sounds like your PKCS#11 application (libp11?) doesn't honour the `CKA_ALWAYS_AUTHENTICATE` flag to (re-) validate the PIN.

**Comment by frankmorgner** [comment]
By the way, `pin_cache_ignore_user_consent = true` has been created specifically to make applications work that don't handle `CKA_ALWAYS_AUTHENTICATE` correctly...

**Comment by dengert** [comment]
@mouse07410 
PKCS\#11 2.40 section "4.9 Private key objects" says: "Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC immediately after a cryptographic operation using the key has been initiated (e.g. after C_SignInit)."

You also said: "I was under impression that if the user is not logged in, then C_SignInit() must fail with CKR_USER_NOT_LOGGED_IN...?"

Your order is wrong and missing a call to C_Login(CKU_CONTEXT_SPECIFIC) 

 1. Checked for CKA_ALWAYS_AUTHENTICATE  on private key and save for later. 

 2. Issue C_SignInit()  

 3. If  CKA_ALWAYS_AUTHENTICATE then get the PIN and call C_Login( pin, CKU_CONTEXT_SPECIFIC) 

 4. Issue C_Sign()   C_Sign could fail for a number of reasons. 

Note C_SignInit() can fail with CKR_USER_NOT_LOGGED_IN not because of CKA_ALWAYS_AUTHENTICATE as the test to see if CKA_ALWAYS_AUTHENTICATE so a C_Login(CKU_CONTEXT_SPECIFIC) can be done. C_Sign can return  CKR_USER_NOT_LOGGED_IN which could be caused by C_Login(CKU_CONTEXT_SPECIFIC) not having been called or some other reasons like pin cache limit. 

There are tow types of logins:
  1. The normal C_Login which gives access to all the objects

  2. the CKU_CONTEXT_SPECIFIC C_Login to be used to satisfy CKA_ALWAYS_AUTHENTICATE 
 
C_SignInit could fail for (1) but should not for (2).

**Comment by dengert** [comment]
@frankmorgner  You said: "... doesn't honour the CKA_ALWAYS_AUTHENTICATE flag to (re-) validate the PIN."

It is not clear from PKCS\#11 if the same PIN has to be used for a normal C_Login or a C_Login(CKU_CONTEXT_SPECIFIC)  So technically it is not a re-validate the PIN. But so far it has always been  the same PIN because most cards expect the same pin.

**Comment by dengert** [comment]
@mouse07410  As @frankmorgner  pointed out: "...pin_cache_ignore_user_consent = true has been created specifically to make applications work that don't handle CKA_ALWAYS_AUTHENTICATE correctly..."

And yes there are policy issues  as the intent is to have the user authorize every use of the private key with the  CKA_ALWAYS_AUTHENTICATE by giving the PIN again. And the only way to really enforce it is if the card has a pin pad reader built in. Next best is a pin pad reader. 

Early version of Mozilla NSS did not support CKA_ALWAYS_AUTHENTICATE thus the need to have this option in opensc.conf. One of the thing I worked on before I retired was to get Mozilla to support it.  Many applications still don't support it.

**Comment by mouse07410** [comment]
> What test program are you referring to?

This:
```
. . . [ caller performs successful decryption on the token that involves logging in ] . . .
int sign(const unsigned char *in, const size_t inlen, unsigned char **out, size_t *olen, ENGINE *e)
{
	int            rv      = -1;
	EVP_PKEY      *privkey = NULL;
	EVP_PKEY_CTX  *ctx     = NULL;
	PW_CB_DATA     cb_data;

	cb_data.password = NULL;
	cb_data.prompt_info = "PIN:"; 

	privkey = ENGINE_load_private_key(e, "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private", NULL, &cb_data);
	if (privkey == NULL) {
		fprintf(stderr, "sign: failed to get handle to privkey id_03\n");
		goto end;
	}

	ctx = EVP_PKEY_CTX_new(privkey, NULL);
	EVP_PKEY_free(privkey);
	if (ctx == NULL) {
		fprintf(stderr, "sign: failed to create context\n");
		goto end;
	}
	rv = EVP_PKEY_sign_init(ctx);
	if (rv <= 0) {
		fprintf(stderr, "sign: failed to initialize context (rv=%d)\n", rv);
		goto end;
	}
	rv = EVP_PKEY_CTX_set_rsa_padding(ctx, SIGN_PADDING);
	if (rv <= 0) {
		fprintf(stderr, "sign: failed to initialize sign_init ctx or set padding (rv=%d)\n", rv);
		goto end;
	}

	// Prepare for signing - determine the length of the signature
	*olen = 0;
	rv = EVP_PKEY_sign(ctx, NULL, olen, in, inlen);
	if ((rv <= 0) || (*olen == 0)) {
		fprintf(stderr, "sign: failed to get required output buf len (rv=%d)\n", rv);
		goto end;
	}
	*out = OPENSSL_malloc(*olen);
	if (*out == NULL) {
		fprintf(stderr, "sign: failed to allocate output buf (%1lu bytes)\n", *olen);
		rv = -1;
		goto end;
	}
	rv = EVP_PKEY_sign(ctx, *out, olen, in, inlen);
	if (rv <= 0) {
		OPENSSL_free(*out); *out = NULL;
		fprintf(stderr, "sign: failed to sign (rv=%d)\n", rv);
		goto end;
	}
        printf("sign: sign returned %d (%1lu bytes)\n", rv, *olen);

	/* Cleanup - tear down OpenSSL constructs used here */
end:
	ERR_print_errors_fp(stderr);
	if (ctx != NULL)
		EVP_PKEY_CTX_free(ctx);

	return rv;
}
```

> By the way, `pin_cache_ignore_user_consent = true` has been created specifically to make applications work that don't handle `CKA_ALWAYS_AUTHENTICATE` correctly...

Understood. The question is - whose application doesn't handle `CKA_ALWAYS_AUTHENTICATE` correctly? Is it the current OpenSC itself? Is it libp11? Is it the above code?

Also, PKCS#11 says that authentication must immediately precede the operation on a `CKA_ALWAYS_AUTHENTICATE` key. But if the user does a "normal" login to the token, and the only subsequent operation is (for example) "sign" (`C_SignInit()` + `C_Sign()`) then forcing the re-auth after `C_SignInit()` would seem excessive. 

So there seems to be a need for awareness of whether there has been a crypto operation between the last `C_Login()` and this `C_SignInit()` (or whatever operation is requested on a `CKA_ALWAYS_AUTHENTICATE` key, which usually - but as I understand - not always is a `SIGN key`). And (re-)issuing `C_Login()` in that case.

>  Can you reproduce the problem with pure OpenSC?

How would I try? I'll be happy to validate with pure OpenSC.

> Sounds like your PKCS#11 application (libp11?) doesn't honour the `CKA_ALWAYS_AUTHENTICATE` flag to (re-) validate the PIN.

Possible, and I leave the answer to @mtrojnar . However, this code https://github.com/OpenSC/libp11/blob/master/src/p11_rsa.c#L100-L116
seems to do exactly what @dengert explained. Please correct me if I'm misreading either.

**Comment by dengert** [comment]
@mouse07410 
Looking at the SPY log, show in 186: C_GetAttributeValue that it got  CKA_ALWAYS_AUTHENTICATE  True 
but there is no call to C_Login between 187: C_SignInit and 188: C_Sign so C_Sign fails with CKR_USER_NOT_LOGGED_IN as per PKCS\#11. 

The opensc-debug.log shows in line 11957  69 82, Security status not satisfied, because the PIV specs call for  no commands to the card between the VERIFY  and the crypto command, and this is enforced by the card.
 
So these look normal.  The OpenSC is doing what is expected. This is an example of an application that does not handle CKA_ALWAYS_AUTHENTICATE  correctly, and wold be a good use of `pin_cache_ignore_user_consent = true` until the application is fixed.

**Comment by dengert** [comment]
In the p11 code, it looks like pkcs11_authenticate was designed to handle the CKA_ALWAYS_AUTHENTICATE and it will call C_Login CKU_CONTEXT_SPECIFIC `if (!kpriv->always_authenticate)`

but the code in p11_rsa,c (and I assume code in p11_ec.c) is calling it to do two different functions,
 1. Handle  CKA_ALWAYS_AUTHENTICATE 
 2. Handle if the user is really not logged in for what ever other reason. 

Lines 102, 103 and lines 111, 112  will catch (2.). 
It is not catching (1.) at all because C_SignInit returns OK. 
But  it needs at least a call to pkcs11_authenticate between 104 and 105. 

I would rewrite pkcs11_authenticate and pass in another parameter, to say which type test is it doing, to try and login normally or to do a  CKU_CONTEXT_SPECIFIC login if needed for  CKA_ALWAYS_AUTHENTICATE.

**Comment by dengert** [comment]
Actually, it looks like p11_ec.c is designed to catch (1.) and not (2.)

210         rv = CRYPTOKI_call(ctx,
211                 C_SignInit(spriv->session, &mechanism, kpriv->object));
212         if (!rv)
213                 rv = pkcs11_authenticate(key);
214         if (!rv)
215                 rv = CRYPTOKI_call(ctx,
216                         C_Sign(spriv->session, (CK_BYTE *)msg, msg_len, sigr    et, &ck_sigsize));

The opensc-tool.c could use some looking at too.

**Comment by mtrojnar** [comment]
Okay.  I will fix it.

**Comment by dengert** [comment]
@mouse07410  you said: "Also, PKCS#11 says that authentication must immediately precede the operation on a CKA_ALWAYS_AUTHENTICATE key. But if the user does a "normal" login to the token, and the only subsequent operation is (for example) "sign" (C_SignInit() + C_Sign()) then forcing the re-auth after C_SignInit() would seem excessive."

The devil is in the details. It depend on the card and if the card enforces VERIFY PIN  immediately precede the crypto operation which is what the PIV cards do. After a normal login, the card driver or application may read a number of objects/file off a card which include commands to the card. For example a driver  may have to read some private key info.  or an application may do a C_Login then read certificates off the card.  A VERIFY Lc=0 to test the state of the card may count an an extra command and invalidate the "immediately precede".  Some other application may try reading the card too. And some card (I don't know of any) could have a different VERIFY operation to enforce the VERIFY PIN  immediately precede the crypto operation. Or it could be two different PINS. 

The card issuer implements policy by requiring CKA_ALWAYS_AUTHENTICATE on some keys. For example the first C_Login is done early to find what private keys are available and what are the attributes. Then the user walks away from their desk to get a cup of coffee, then comes back and decides to sign something. Is that "immediately before"? What if someone else got to his computer while he was  getting the coffee and did a sign? (He should never have walked away and left the card in the reader, but that happens.)

So although it sounds simple, it is not easy to implement, especially if multiple applications can access the card. The PKCS\#11 and PKCS\#15, PCSC and various card standards also make it difficult.

**Comment by mouse07410** [comment]
> The devil is in the details. . . . although it sounds simple, it is not easy to implement, especially if multiple applications can access the card. The PKCS#11 and PKCS#15, PCSC and various card standards also make it difficult.

Yes, you are absolutely correct. It is not easy, and as we both know, some cards interpret the standard differently, thus complicating what's already complicated enough.

I discussed this issue with our UI people, and they unanimously told me that from the User Interface point of view it would *not* be good if a user would be prompted for a PIN twice in a row for the same operation (i.e., once to "login to the token" so the middleware can figure out what private keys are available, and the second time to "actually sign a file or an outgoing email").

All of your points are good, no argument here. But the above is also a valid concern...

**Comment by mouse07410** [comment]
> Looking at the SPY log, show in 186: C_GetAttributeValue that it got `CKA_ALWAYS_AUTHENTICATE` `True` but there is no call to `C_Login` between 187: C_SignInit and 188: C_Sign so C_Sign fails with CKR_USER_NOT_LOGGED_IN as per PKCS#11.

But @dengert, there is a call to `C_Login()` at https://github.com/OpenSC/libp11/blob/master/src/p11_rsa.c#L102. 

And https://github.com/OpenSC/libp11/blob/master/src/p11_ec.c#L212-L213 seem to handle both (1) and (2), because `C_SignInit()` shouldn't return `CKR_OK` unless the token is logged in and ready to perform signing operation. Right?

> But it needs at least a call to pkcs11_authenticate between 104 and 105.
(in https://github.com/OpenSC/libp11/blob/master/src/p11_rsa.c#L100-L116). But that's what presumably is done at 102. Or are you suggesting that `pkcs11_authenticate()` should be called if return code is `USER_NOT_LOGGED_IN` *or* `OK`? 

It would be great it one could track the card state/status... Is it possible?

Or should we (I) just be satisfied with `pin_cache_ignore_user_consent = true` as the lesser of evils?

> I would rewrite pkcs11_authenticate and pass in another parameter, to say which type test is it doing, to try and login normally or to do a `CKU_CONTEXT_SPECIFIC` login if needed for `CKA_ALWAYS_AUTHENTICATE`.

Yes, probably a good idea...

**Comment by dengert** [comment]
@mouse07410  looks like https://github.com/OpenSC/libp11/blob/master/src/p11_rsa.c#L102 was just changed by https://github.com/OpenSC/libp11/commit/6ef8aed5cebb184c82026051cd2a0fb750000eae about 44 minutes ago. So I am not sure what you were looking at. 

Your traces never did a C_Login with CKU_CONTEXT_SPECIFIC.  Try the new master. 

but still note that pkcs11_authenticate currently only does a C_Login with CKU_CONTEXT_SPECIFIC which will only work if the user is already logged in. So it should fail or do nothing  about addressing CKR_USER_NOT LOGGED_IN  from C_SignInit. 

Any re-authenticate needs to address both (1.) and (2.)

**Comment by mouse07410** [comment]
> but still note that pkcs11_authenticate currently only does a C_Login with CKU_CONTEXT_SPECIFIC which will only work if the user is already logged in. So it should fail or do nothing about addressing CKR_USER_NOT LOGGED_IN from C_SignInit.

I think I see your point. But (2) should not matter because for most (all?) tokens you can't even *get* to a private key without logging in first. So the likelihood of a user not being logged in before attempting to sign is low. In fact, I've never experienced it so far.

What do you think about it?

**Comment by dengert** [comment]
If the pin cache limit is exceeded or the some other application grabs the card it can get logged out and I believe C_SignInit may return CKR_USER_NOT_LOGGED_IN. @frankmorgner is that true? As you point out it is low probability, but for completeness it should be addressed. 

Also keep in mind that any solutions should also work with a pin pad reader. I.E. no pins can be cache at any level.

As for the PIV driver tries to load the 4 main certs but not the history certs in the driver init routine to avoid doing extra commands after the C_Login.  Loading the certs in effect loads the public keys and the private key info from the public keys. It also uses the same VERIFY command to the card, so in **theory** it could get away with one login if the caller does not try and load a bunch of other objects or force other commands to the cards. 

So carefully crafted PKCS#11 code could load up all the objects it needs before the first C_Login, then skip the first C_Login needing CKU_CONTEXT_SPECIFIC. If the C_Sign failed, it could retry the the C_SignInit, pkcs11_authenticate (or equivalent code) to do the C_Login with CKU_CONTEXT_SPECIFIC then the C_Sign should work.  

No guarantee that this would work and it may not work for other cards or other applications or tokend or minidriver. 

The carefully crafted code should also worry about the time between the  initial C_Login and the time to the  C_Login with CKU_CONTEXT_SPECIFIC  to avoid the "user walked away for too long" scenario.

If you want to try implementing this using PIV type cards, first look at a SPY trace and compare to the opensc-debug trace to see if any commands are issued to the card between the first C_Login and when the first C_Login with CKU_CONTEXT_SPECIFIC is sent. If there are none then this might work. 
I leave that up to you and your MIT friend that don't like the double login to track this down. 

If the above only works some of the time, users might be surprised that they are being prompted a second time some of the time, that may be more confusion then always being prompted twice. It might look to them that some software is doing an extra sign operation without their permission.

**Comment by dengert** [comment]
@mouse07410 
The above will not work with your test program, because you said:
". . . [ caller performs successful decryption on the token that involves logging in ] . . ."
and the logs show a decrypt is done between the initial C_Login and the c_Sign.
If you can rewrite the test program to do the sign first then the decrypt the above might work. 

So if the test program is meant to show what you will be doing in production and you and your UI people are willing to violate the inherent PIV policy of the user must enter PIN to do a sign using the sign key, you have two choices:

 1. `use pin_cache_ignore_user_consent = true`

 2.  If you are using the Yubikey you could use one of the history certs/keys to do the sign or use the auth key. But the certs must have the correct keyUsage and other attributes.

**Comment by dengert** [comment]
@mouse07410 Why are you using the sign key? You test program is designed for login. 
 PKINIT works fine with just a single key, the auth key, as does SSL/TLS with client certificates. 

The PIV sign key is designed to sign document or emails, the sort of operations that require "norepudiation".
 
If you can use just the auth key, you wold not have to deal with CKU_CONTEXT_SPECIFIC.

**Comment by dengert** [comment]
@frankmorgner  this issue could be renamed or closed, because the issue is in libp11 
 and solved by https://github.com/OpenSC/libp11/commit/6ef8aed5cebb184c82026051cd2a0fb750000eae
The issue of how to avoid  a second prompt for the PIN if possible is a separate issue.

**Comment by mouse07410** [comment]
> If you can rewrite the test program to do the sign first then the decrypt the above might work.

Yes, I understand. The idea was to see if an application can issue a series of user-authorized signatures (in addition to doing something else, like encrypting/decrypting documents).

> Why are you using the sign key? . . . The PIV SIGN key is designed to sign document or emails . . .

That's exactly why. 

> If you can use just the PIV AUTH key, you wold not have to deal with CKU_CONTEXT_SPECIFIC.

Yes, that's my intention for remote logins. But it doesn't work for document signature, and based on the standard PIV-specified attributes - not for document encryption (although KEY MAN key can be used for that with PIV AUTH, as both don't have ALWAYS_AUTHENTICATE set).

> this issue could be renamed or closed, because the issue is in libp11
and solved by OpenSC/libp11@6ef8aed

Correct. I'm closing it.

> The issue of how to avoid a second prompt for the PIN if possible is a separate issue.

Yes. And it looks like it's a darn-hard-to-address one. Though perhaps you and @mtrojnar can come up with an idea...?

**Comment by mtrojnar** [comment]
> I would rewrite pkcs11_authenticate and pass in another parameter, to say which type test is it doing, to try and login normally or to do a CKU_CONTEXT_SPECIFIC login if needed for CKA_ALWAYS_AUTHENTICATE.

> And I would add the same logic around every crypto operation with a private key. Today's cards only do CKA_ALWAYS_AUTHENTICATE for signing keys, but PKCS#11 allows for CKA_ALWAYS_AUTHENTICATE for any private key.

It recommend against adding additional complexity to the code unless there is a real use case or security risk associated.  In other words: if it ain’t broke, don’t fix it.

**Comment by dengert** [comment]
@mouse07410 
Yes it is "darn-hard-to-address" because of the way PKCS\#11 specifications are written, and the various ways  "CKA_ALWAYS_AUTHENTICATE" may be implemented (and enforced) in a PKCS\#11 module and if the card itself enforces some sort of "CKA_ALWAYS_AUTHENTICATE". Cards try to do the enforcement as an attempt to enforce policies of the issuer. 

In your case it looks like you and your organization will be issuing certificates and provisioning Yubico tokens, in which case you get to set the policies. So what policies do you want? 

Do you want "CKA_ALWAYS_AUTHENTICATE" on the sign key or not?

Are Yubico tokens the right choice for you?

Do you wish to use the Microsoft Windows built in code with these cards?

Do you plain or expect you will have to use U.S. gov issued PIV cards? (In which case the policies are set by NIST and the issuing agency.)  

The Yubico is not a real PIV card. It does not enforce all the NIST requirements and adds some features of its own. The opensc card-piv.c and pkcs15-piv.c were written to the NIST specs and code added to support some of the Yubico idiosyncrasies.  One of these is to allow certificates and keys in the history to be used in ways not in the NIST specs, i.e. you could have a sign key and cert which does not require  "CKA_ALWAYS_AUTHENTICATE"

I remember newer Yubico cards have some ways to force or not force "CKA_ALWAYS_AUTHENTICATE" for keys and also set no login is required to use specific keys. The card-piv.c and pkcs15-piv.c don't try and read these bits today but they could. I am not going to make any changes to do this unless you are going to use them to turn off "CKA_ALWAYS_AUTHENTICATE". If you want this feature, find the Yubico documentation for me.  You will need it to set the bits when you issue the cards.

**Comment by dengert** [comment]
@mtrojnar 
The change you provided fixes the  "CKA_ALWAYS_AUTHENTICATE" issue. But it does not fix issues where libp11 may be called by a long running process such as a web browser that establishes a session.
PKCS\#11 may loose the login state to the card for a number or reasons such as some other application
accesses the card and causes the login state to be lost. So it may not be a problem today, it may eventually be a problem.  Add it to the TODO list.

**Comment by mtrojnar** [comment]
> PKCS#11 may loose the login state to the card for a number of reasons

1. I'm not convinced whether this potential problem that should be solved by libp11, and not the PKCS#11 module, p11-kit or the application itself...
2. Why would this problem be limited to the login state?  I guess at least `C_Initialize` args could also be affected.
3. Was the PKCS#11 API designed to allow a module to be simultaneously used by more than one **application** at a given time?

**Comment by mouse07410** [comment]
> Cards try to do the enforcement as an attempt to enforce policies of the issuer.

I'm not aware of (and am not using) any card that does *not* enforce `CKA_ALWAYS_AUTHENTICATE`.

> In your case it looks like you and your organization will be issuing certificates and provisioning Yubico tokens, in which case you get to set the policies. So what policies do you want? Do you want "CKA_ALWAYS_AUTHENTICATE" on the sign key or not?

The answer is yes, because we're adopting NIST policies whenever it makes sense (or whenever it is required :). This appears to match both.

> Are Yubico tokens the right choice for you?

Yes, and so are CAC and PIV.

> Do you wish to use the Microsoft Windows built in code with these cards?

:-)  I don't. 

Others at the organization may. :-)

> Do you plan or expect you will have to use U.S. gov issued PIV cards? (In which case the policies are set by NIST and the issuing agency.)

Oh yes.

> The Yubico is not a real PIV card. It does not enforce all the NIST requirements and adds some features of its own. The opensc card-piv.c and pkcs15-piv.c were written to the NIST specs and code added to support some of the Yubico idiosyncrasies. One of these is to allow certificates and keys in the history to be used in ways not in the NIST specs, i.e. you could have a sign key and cert which does not require "CKA_ALWAYS_AUTHENTICATE"

Yeah... And if you recall, I was against that addition. ;-)

In any case, the solution must work with PIV (NIST-blessed PIV), so even if there was a way to coerce Yubikey to violate, it wouldn't be acceptable here.

> I remember newer Yubico cards have some ways to force or not force "CKA_ALWAYS_AUTHENTICATE" for keys and also set no login is required to use specific keys. The card-piv.c and pkcs15-piv.c don't try and read these bits today but they could. I am not going to make any changes to do this unless you are going to use them to turn off "CKA_ALWAYS_AUTHENTICATE". If you want this feature, find the Yubico documentation for me. You will need it to set the bits when you issue the cards.

To be honest, I'd rather not deviate from NIST here. I probably could find the Yubico docs, but I'd rather not have "ALWAYS_AUTHENTICATE" turned off - especially if the card prefers it set on.

I am considering *other* additions - being able to set the "must-touch" bit on a newly-issued card (in addition to entering a PIN, you have to touch the touch-pad of the *card itself* in order for the key operation to be allowed). That's a neat Yubikey-4 feature. But I'm sure that not every user would want that.

**Comment by dengert** [comment]
@mtrojnar 
Starting with (3.) I would say yes. Going back to a paper copy of PKCS\#1 v2.01 1997, and a word .doc version v 2.11 from 2001, and V2.30  Section 5.1 "Design Goals" and V2.30 Section 6.2 Design goals say: "Cryptoki was intended from the beginning to be an interface between applications and all kinds of portable cryptographic devices,..."

Then later says: "A secondary goal was resource-sharing.  As desktop multi-tasking operating systems become more popular, a single device should be shared between more than one application.  In addition, an application should be able to interface to more than one device at a given time."

I read that as I could use the same token for login to the desktop, then use it in a browser like FireFox to access a website, use with Thunderbird for encrypted and signed e-mail, SSH to use the key on the token  and rdesktop to give access to the card to some remote computer. The browser, and E-mail program are two prime examples of a long running applications that want to share the token.  Login to the workstation may keep monitoring if the card is still in the reader, and lock the screen if it is withdrawn.  None of the above use libp11. FireFox and Thunderbird use Mozilla NSS that calls PKCS\#11 modules.  

But PKCS\#11 leaves it up to the operating system how control the access between applications of a single user and applications of a different user. The method of choice these days is a single PCSC process for one machine that controls access to the token and can allow multiple applications access the tokens.

PCSC hints at control of access by user, i.e. the user at the console, but that appears to be left up to the OS and has the same problems as other physically attached devices like Audio, Camera, DVD, Mouse, Keyboard.  

PCSC does have ways to lock access to a token exclusively, shared or for an operation. The OpenSC opensc.conf file has a number of parameters to says how OpenSC based code would do this. Non OpenSC PKCS\#11 or even none PKCS\#11 code that use PCSC may do what ever they want. 

One could request exclusive using the opensc.conf parameters to request exclusive use of the token untoll the application ends. But doing this would mean that you would have quit one application in order to let an other application use the token.  This can be a problem for the user. 

In point (2.) you say: "Why would this problem be limited to the login state" Its not. But losing the login state requires reentering the PIN, which is what @mouse07410 it trying to avoid. Any changes to the token by one application is not easily recognized by other applications which is a problem. 

In point (1.) you say: "I'm not convinced whether this potential problem that should be solved by libp11"
I am not either. That's why I said add to a TODO list. But any application using PKC\#11 needs to be ready to handle any return code such as CKR_USER_NOT_LOGGED_IN. It can call it an error, and force the calling application to do something, like abort or libp11 can use an UI to prompt the user to get the PIN again.

Note that OpenSC PKCS\#11 can cache the PIN and avoid many CKR_USER_NOT_LOGGED_IN situations up to a limited number of times, so this mitigates the problem. But with a pin pad reader the PIN goes from the reader to the card. So it is never seen by the host so it can not be cached.

**Comment by mouse07410** [comment]
> I recommend against adding additional complexity to the code unless there is a real use case or security risk associated. In other words: if it ain’t broke, don’t fix i

I missed this, sorry. The point is - it *is* broke, and there *is* a real use case. The problem is - it is unclear whether a generic solution is even possible, given that different cards misunderstood PKCS#11 in different ways... Still, this one would be nice to solve, if it turns out doable.

**Comment by dengert** [comment]
I will still try and look at this. It is similar to libp11 issues with SafeNet.
