### ISSUE TITLE
feitian epass2003 is not working with opensc 0.17.0 on Fedora 26

### ISSUE THREAD

**Issue by sandys** [OpenSC/OpenSC#1115]
```
opensc-tool --list-readers                                                                                                                               
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             FT ePass2003Auto 00 00
```

pkcs15-init --erase-card -vvv  **(this works fine)**
pkcs15-init --create-pkcs15 --profile pkcs15+onepin --label "sandys" -vvv **(this works fine)**
pkcs15-init --auth-id 1 --generate-key rsa/2048 --key-usage sign,decrypt -vvv **(this fails)**

> Using reader with a card: FT ePass2003Auto 00 00
> PKCS#15 binding failed: Unsupported card
> 

the detailed logs have been attached. grep for "sss>" to see the different commands that i have run separately.
[debug.log.zip](https://github.com/OpenSC/OpenSC/files/1191090/debug.log.zip)

> 
> uname -a                                                                                                                                                 
> Linux menzoberranzan 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> 
> LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
> Distributor ID:	Fedora
> Description:	Fedora release 26 (Twenty Six)
> Release:	26
> Codename:	TwentySix

> 
> Installed Packages
> Name         : opensc
> Version      : 0.17.0
> Release      : 1.fc26
> Arch         : x86_64
> Size         : 3.3 M
> Source       : opensc-0.17.0-1.fc26.src.rpm

> Name         : pcsc-tools
> Version      : 1.4.25
> Release      : 2.fc26
> Arch         : x86_64
> Size         : 836 k
> Source       : pcsc-tools-1.4.25-2.fc26.src.rpm
> 
> Name         : pcsc-lite-ccid
> Version      : 1.4.27
> Release      : 1.fc26
> Arch         : x86_64
> Size         : 1.4 M

**Comment by sandys** [comment]
its working with older version of opensc

> Name         : opensc
> Version      : 0.16.0
> Release      : 5.20161016git0362439.fc26
> Arch         : x86_64
> Size         : 3.1 M
> Source       : opensc-0.16.0-5.20161016git0362439.fc26.src.rpm
>

**Comment by frankmorgner** [comment]
Did you check https://github.com/OpenSC/OpenSC/pull/1110?

**Comment by dengert** [comment]
See #1110 near end for new possible fix for SM handling of Wrong Length.

**Comment by FeitianSmartcardReader** [comment]
@sandys already test with #1127 and make sure works.
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs15-init --create-pkcs15 --profile pkcs15+onepin --label "sandys"
Using reader with a card: Feitian ePass2003
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Please type again to verify: 
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs15-init --auth-id 1 --generate-key rsa/2048 --key-usage sign,decrypt
Using reader with a card: Feitian ePass2003
User PIN [User PIN] required.
Please enter User PIN [User PIN]: 
Hongbins-MacBook-Pro:OpenSC Ben$ 
Hongbins-MacBook-Pro:OpenSC Ben$ 
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs15-init --auth-id 1 --generate-key rsa/2048 --key-usage sign,decrypt 
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs15-tool -D
Using reader with a card: Feitian ePass2003
PKCS#15 Card [sandys]:
	Version        : 0
	Serial number  : 0900000000000000
	Manufacturer ID: EnterSafe
	Last update    : 20170810083556Z
	Flags          : EID compliant
PIN [User PIN]
	Object Flags   : [0x3], private, modifiable
	ID             : 01
	Flags          : [0x32], local, initialized, needs-padding
	Length         : min_len:4, max_len:16, stored_len:16
	Pad char       : 0x00
	Reference      : 1 (0x01)
	Type           : ascii-numeric
	Path           : 3f005015

Private RSA Key [Private Key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x2E], decrypt, sign, signRecover, unwrap
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 2048
	Key ref        : 0 (0x0)
	Native         : yes
	Path           : 3f0050152900
	Auth ID        : 01
	ID             : fef533e2f9e2cf951cee26a71fdf1d4905a031b0
	MD:guid        : af63393d-58e2-87a1-f111-9a9241a22cf0

Public RSA Key [Private Key]
	Object Flags   : [0x2], modifiable
	Usage          : [0xD1], encrypt, wrap, verify, verifyRecover
	Access Flags   : [0x0]
	ModLength      : 2048
	Key ref        : 0 (0x0)
	Native         : no
	Path           : 3f0050153000
	ID             : fef533e2f9e2cf951cee26a71fdf1d4905a031b0

Hongbins-MacBook-Pro:OpenSC Ben$

**Comment by sandys** [comment]
@FeitianSmartcardReader do you know when this patch will be released to general repositories ? a lot of our staff is facing this issue now. I am having to manually lock package version to opensc-0.16.0-5.20161016git0362439.fc26.x86_64 .. which is a very cumbersome process.

**Comment by Jakuje** [comment]
@sandys Once the fixes will be merged upstream, I can build you a package in Fedora. But please, open me a bug in Red Hat bugzilla ideally with the link to the PR/patches that are needed to make it working:
https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

The next upstream relase will not be earlier than in a year if I am right.

**Comment by sandys** [comment]
@FeitianSmartcardReader @Jakuje is there a timeline for the release to distros/upstream ? Because without this fix we are having a lot of issues on linux. 

today we are manually installing http://rpmfind.net/linux/centos/7.4.1708/os/x86_64/Packages/opensc-0.16.0-5.20170227git777e2a3.el7.x86_64.rpm to get this to work

**Comment by Jakuje** [comment]
As I already wrote, there is no plan to release another snapshot version, before there will be OpenSC 0.18.0  released later this year. If you wish to have this or some other feature in Fedora, please, open a bug in Red Hat bugzilla, ideally with the features you need to have fixed from upstream and I can update a package for you.

**Comment by rvalle** [comment]
@FeitianSmartcardReader what is the recommended way to workaround this issue?
Or having your product not working during one and half years is the plan....

**Comment by sandys** [comment]
We are also facing trouble with this constantly and are considering moving
away from epass2003.

It's been a year since this issue has been open and there has been no
update even though a bug fix is supposedly available.

Not sure whom we must request to get this to happen. But if anyone is
paying attention, this is a HUGE issue and it would be a big favor if
someone could just push an update with this to the Ubuntu/Fedora repos.

**Comment by FeitianSmartcardReader** [comment]
@rvalle @sandys the issue already solved and merger in 0.18, may I know what's the current question from you guys?

**Comment by sandys** [comment]
these are NOT available in any distros. Current available version on fedora
latest is

Available Packages
Name         : opensc
Version      : 0.17.0
Release      : 4.fc27
Arch         : i686
Size         : 1.1 M
Source       : opensc-0.17.0-4.fc27.src.rpm
Repo         : updates
Summary      : Smart card library and applications
URL          : https://github.com/OpenSC/OpenSC/wiki
License      : LGPLv2+
Description  : OpenSC provides a set of libraries and utilities to work
with smart cards. Its
             : main focus is on cards that support cryptographic
operations, and facilitate
             : their use in security applications such as authentication,
mail encryption and
             : digital signatures. OpenSC implements the PKCS#11 API so
applications
             : supporting this API (such as Mozilla Firefox and
Thunderbird) can use it. On
             : the card OpenSC implements the PKCS#15 standard and aims to
be compatible with
             : every software/card that does so, too.

**Comment by martinpaljak** [comment]
@sandys If the fix is in OpenSC repository, please take this discussion to Fedora package maintainers - I'm sure this can be backported if necessary.

**Comment by sandys** [comment]
@martinpaljak from what I understand based on this comment - https://github.com/OpenSC/OpenSC/issues/1115#issuecomment-361948230 - there is no plan to release this package upstream anytime soon.

**Comment by rvalle** [comment]
Totally agree with @sandys if there is no package the fix is not available (except for testing).

It is very worrisome that Fedora does not take security more seriously. For a package like OpenSC, 18 months to incorporate fixes does not seem appropriate. 

Of course we can push for fixes being back-ported, but again, this is the job of @FeitianSmartcardReader , isn't it?

**Comment by Jakuje** [comment]
I wrote already two times, that if you wish to have something fixed *in Fedora*, [open *a Fedora bug*](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=opensc) and I will update OpenSC package **in Fedora**. If I would have a bug in September, you would have it fixed in September and I would not forget about this issue like I already did two times since I can not follow all the closed issues here.

(from the previous comments)
> If you wish to have this or some other feature in Fedora, please, open a bug in Red Hat bugzilla, ideally with the features you need to have fixed from upstream and I can update a package for you.

(from the other comment)
> @sandys Once the fixes will be merged upstream, I can build you a package in Fedora. But please, open me a bug in Red Hat bugzilla ideally with the link to the PR/patches that are needed to make it working.

In Opensource, it is not anyones job. There are just people who implemented it, who wants to use it and who can bring it to them throughout distributions in their time. If the third group does not hear from the second one about the urgent need of the fix implemented by the first group, who to blame?

**Comment by sandys** [comment]
hi @Jakuje we are not aware of the specific constraints of this project and which is why all of us were puzzled on what to do. In other projects (e.g. docker/moby, etc), maintainers are able to take a call on their own on when to backport merge certain fixes into distro. We were not aware that one of us would have to create a ticket and this would not be done by you unilaterally.

I have gone ahead and created one - https://bugzilla.redhat.com/show_bug.cgi?id=1558099  . I hope that is sufficient.

**Comment by rvalle** [comment]
I totally understand @Jakuje 
I am not in a position to recommend a backport of code I have not reviewed. I can only say that the issue is still ongoing, and my Opensource job here can be to test for you in my environment when you need.

I don't know if @sandys is in a more knowledgeable position than I am, but I think that it is @FeitianSmartcardReader who should take an active role in following up on this kind of issue.

@sandys thanks for opening the issue

**Comment by MukiEX** [comment]
For what it's worth, I'm still not getting any compatibility with an epass2003 device on 0.18.0:

http://pasteall.org/962740/bash

**Comment by frankmorgner** [comment]
Your issue is not related, your system is missing the smart card driver.
