### ISSUE TITLE
Feitian ePass2003 token not working with current opensc versions/distro

### ISSUE THREAD

**Issue by btassite** [OpenSC/OpenSC#1660]
### Problem Description

Feitian ePass2003 token works without issues with:
- opensc 0.13 and OpenVPN 2.3.2 under Ubuntu 14.04
- opensc 0.15 and OpenVPN 2.4.4 under Ubuntu 18.04 (package held, since 0.17 current for 18.04)

token is not recognized at all by (token LED remains steady green):
- opensc 0.17 (Ubuntu 18.04)
- opensc 0.18 (Ubuntu 18.10)

works partially with:
- opensc 0.15 and OpenVPN 2.4.4 or 2.4.6 under Ubuntu 18.10

Works partially means the token LED is blinking on access and all these commands show output but OpenVPN hangs after trying to bring up tun0:
$ opensc-tool -l
$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -L
$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -O
$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -T
$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -I
$ openvpn --show-pkcs11-ids /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
$ pkcs15-tool -D

### Proposed Resolution

As the token *seems* to work but  Just a gut feeling that Ubuntu 18.10 has some part which isn't quite as compatible as 18.04 in combination with perhaps the dependencies of opensc 0.15 (opensc-pkcs11_0.15 and/or libreadline6), so ideally opensc 0.18 or newer should be made to work with the token so these don't play a role.

### Steps to reproduce

Install Ubuntu 18.10, install openvpn, install opensc from repo, plug in Feitian ePass 2003, try pkcs15-tool -D
or
Install Ubuntu 18.10, install openvpn, install opensc package 0.15 dependencies (opensc-pkcs11_0.15, libreadline6 debs), install opensc 0.15 deb, try to connect with openvpn.

### Logs

upping opensc debug level to 3 generates 3520 lines, I'm not sure how to sanitize the output from all PIN/certs and other sensitive information, if you need specifics from it please ask. From a cursory glance there doesn't seem to be any major errors in there.

The last lines of OpenVPN output (with verbosity 11) after which it hangs:
```
Wed Apr  3 17:04:07 2019 us=531469 /sbin/ip link set dev tun0 up mtu 1500
Wed Apr  3 17:04:07 2019 us=533086 PKCS#11: __pkcs11h_forkFixup entry pid=12612,
activate_slotevent=1
```

Also tried manually bringing tun0 up, giving the interface an IP, adding routes etc. but no traffic is possible.

NB: openvpn needs renaming /bin/systemd-ask-password or you can't put in the token password and it hangs much earlier.

**Comment by btassite** [comment]
Also tried downloading and compiling 0.19, same result: token seems to be read correctly by opensc, but openvpn hangs on trying to bring up tun0.

**Comment by FeitianSmartcardReader** [comment]
@btassite our engineer will take a look tomorrow, I will keep you update, thanks

**Comment by frankmorgner** [comment]
OpenVPN suffers from a problem, that currently requires disabling desktop notifications (`./configure --disable-notify`), see https://github.com/OpenSC/pkcs11-helper/issues/16

**Comment by btassite** [comment]
I read a couple of the related issues and as far as I can understand the desktop notification may be due to a forking issue in opensc, for which I saw related commits in pkcs11-helper, should I rebuild OpenVPN with the disable-notify argument or has this been fixed in opensc nightly?

Also, pkcs11-helper has its own branch, downloaded that but didn't see a configure script so git cloned opensc nightly (Nightly-2019-04-25_bbec50bf) "0.19.0", this compiles with an error:
pkcs11-register.c:25:10: fatal error: pkcs11-register-cmdline.h: No such file or directory
 # include "pkcs11-register-cmdline.h"

I followed the README.md instructions and did ./configure, ./make in ~/Downloads/OpenSC/Nightly-2019-04-25_bbec50bf/opensc-0.19.0/, do I need to get other things or move something around?

**Comment by frankmorgner** [comment]
- the problem with forks should be resolved by updating to both, pkcs11-helper's master and OpenSC's master. I'm unable to verify the fix, however (your feedback is welcome).
- I've added the missing file to the distribution (c671083ee3895ccab0c1e7bc31ba9fbf80e6af51) to fix the build problem

**Comment by btassite** [comment]
pkcs11-helper doesn't have a configure file, how do I compile this?

**Comment by frankmorgner** [comment]
https://github.com/OpenSC/pkcs11-helper/wiki/How-to-compile-pkcs11-helper

**Comment by btassite** [comment]
Thanks, compiled and installed pkcs11-helper, unfortunately openvpn still hangs on the same "/sbin/ip link set dev tun0 up mtu 1500" line.

I presume I don't need to recompile opensc after having compiled/installed pkcs11-helper?

**Comment by btassite** [comment]
Also tried downloading and compiling latest OpenVPN (2.4.7) from https://openvpn.net/community-downloads/.
When running it immediately getting an "Options error: Unrecognized option or missing or extra parameter(s) in xyz.ovpn:26: pkcs11-providers (2.4.7)" error, when commenting that line out an "Options error: Unrecognized option or missing or extra parameter(s) in xyz.ovpn:28: pkcs11-id (2.4.7)" and when commenting that out: "Options error: No client-side authentication method is specified.  You must use either --cert/--key, --pkcs12, or --auth-user-pass".

**Comment by btassite** [comment]
Got rid of the errors by using "./configure --disable-notify --enable-pkcs11", but openvpn still hangs when building the connection, this time on "/sbin/ifconfig tun0 10.11.12.99 pointopoint 10.11.12.1 mtu 1500" (IPs fictitious). This is different from the /sbin/ip link..up line as before, possibly because of other missing options like --enable-iproute2, but the end result is the same.

**Comment by btassite** [comment]
Tried adding --enable-iproute2 and indeed openvpn hangs again on the original /sbin/ip link up line.
But just noticed at the bottom during the build:
configure: WARNING: unrecognized options: --disable-notify

So which branch/version has this option? Since I'm not a developer I would prefer a link :)

**Comment by btassite** [comment]
Oops, --disable-notify is an opensc configuration option, now used that to rebuild opensc, tried with distro's openvpn 2.4.6 package, same thing, hangs on tun0 up line.

**Comment by frankmorgner** [comment]
I was finally able to reproduce the problem with fork and found and fixed an other problem (7449b007688ccce16eb8265cd82a69a945fd38f5). OpenVPN should work in OpenSC's master now.

**Comment by btassite** [comment]
Still the same, configured with --disable-notify, hanging on "ip link set dev tun0 up". Didn't recompile pkcs11-helper as I didn't see new commits since the last time.

**Comment by frankmorgner** [comment]
have a look at https://github.com/OpenVPN/openvpn/pull/121

**Comment by btassite** [comment]
Thanks, that fixed it, tunnel is opened, routes are added and ping through VPN works.
Didn't test with distro's original opensc/pkcs11-helper but at least it's working with opensc 0.19.0 nightly and pkcs11-helper with the commits up to 2019-04-26.
