### ISSUE TITLE
Uninstall script leaves some components behind

### ISSUE THREAD

**Issue by liamdawson** [OpenSC/OpenSC#1898]
### Problem Description

When using the `opensc-uninstall` script, I noted the following:

```shell
$ sudo /usr/local/bin/opensc-uninstall
No receipt for 'org.opensc-project.tokend' found at '/'.
OpenSC has been removed from your system. See you again!

$ pkgutil --pkgs / | grep opensc
org.opensc-project.mac.opensctoken
org.opensc-project.startup

$ launchctl list | grep -Ee '(opensc-notify|pkcs11-register)'
-	0	opensc-notify
-	0	pkcs11-register
```

### Proposed Resolution

* Unload the launchagents on uninstall
* Update the pkgutil cleaning steps

### Steps to reproduce

* Install OpenSC 0.20.0 on macOS Catalina
* Use the `/usr/local/bin/opensc-uninstall` script to uninstall

(Found via https://travis-ci.com/Homebrew/homebrew-cask/jobs/271966033 )

**Comment by notpeter** [comment]
Would it be possible to get a point release which includes this? [Homebrew cask is stuck on 0.19.0](https://github.com/Homebrew/homebrew-cask/pull/75009) until there's a new release with a complete uninstaller. Thanks.

**Comment by frankmorgner** [comment]
I'm afraid this will take at least some more weeks

**Comment by notpeter** [comment]
> homebrew has all the dependencies, why don't you build it from source?

@frankmorgner: Sigh. That's some user-hostile shit.

Why does anyone choose packages over building everything from source (and then take the time to upgrade with each release): because it's a lot faster, easier and ensures any build automation work I do can be shared with other (e.g. via homebrew-cask).

I was just bringing to your attention a distribution channel where users were stuck on a 15month old release with known CVEs was being held back by a bug that's already been fixed.  I've been a package maintainer, I know it's thankless work; I have no sense of entitlement here.

I actually built 0.20.0 from source initially. When I noticed homebrew-cask has a bin I tried to switch to that, realized it was out of date, submitted a [parallel PR #75513](https://github.com/Homebrew/homebrew-cask/pull/75513) but closed it after I saw tests were failing and went searching in the opensc issues and found [PR #75009](https://github.com/Homebrew/homebrew-cask/pull/75009).  But congrats @frankmorgner; you've made it clear contributing to opensc was a mistake and a waste of my time.

**Comment by frankmorgner** [comment]
When creating a package, we're not talking about users but maintainers, so we can expect some expertise. Homebrew brings dependencies like OpenSSL, why install a statically linked one with OpenSC then? Additionally, homebrew is most likely not interested in the CTK or Tokend module, which comes with our binaries. So again, I'd suggest building OpenSC from source, which is done in many homebrew formulas.

Anyway, the original issue is fixed in OpenSC now. We'll make a new release as soon as possible, but I cannot give you a timeline. There is https://github.com/OpenSC/OpenSC/projects/7, however.

**Comment by forrestwilkins** [comment]
It looks like this is still an issue:
```
Error: opensc: uninstall script /usr/local/bin/opensc-uninstall does not exist.
```
How can we resolve this in the meantime?

**Comment by frankmorgner** [comment]
how did you get to this error?

**Comment by cvquesty** [comment]
When you run "brew update" then "brew upgrade", it installs all the components you have outstanding, then it displays that error.  Here's a larger output...

```
==> Upgrading 1 outdated package:
opensc 0.25.1 -> 0.26.1
==> Upgrading opensc
==> Downloading https://github.com/OpenSC/OpenSC/releases/download/0.26.1/OpenSC
Already downloaded: /Users/chs/Library/Caches/Homebrew/downloads/0f1445c2225edc336d90bca7b78e26d5ed8e59d39ddc6c273029aeedc7c47727--OpenSC-0.26.1.dmg
==> Removing launchctl service org.opensc-project.mac.opensc-notify
==> Removing launchctl service org.opensc-project.mac.pkcs11-register
==> Running uninstall script /usr/local/bin/opensc-uninstall
==> Purging files for version 0.26.1 of Cask opensc
Error: opensc: uninstall script /usr/local/bin/opensc-uninstall does not exist.
```

**Comment by frankmorgner** [comment]
> Error: opensc: uninstall script /usr/local/bin/opensc-uninstall does not exist.

this is a problem with the homebrew formula. see this page for reporting https://docs.brew.sh/Troubleshooting
